### ISSUE TITLE
Unable to validate the url in cs-policy

### ISSUE THREAD

**Issue by PaulYounan** [CrowdStrike/gcp-vm-manager-os-policy#10]
Unable to validate https://api.us-2.crowdstrike.com as falcon cloud.

 ```
unrecognized CrowdStrike Falcon Cloud: https://api.us-2.crowdstrike.com
```

**Comment by redhatrises** [comment]
@PaulYounan can you describe how you are providing `--falcon-cloud` cli argument or the `FALCON_CLOUD` environment variable?

**Comment by PaulYounan** [comment]
Hi Gabe, thanks for the response.

I'm setting an environment variable in MacOS.

Curiously, this works if I leave the Evnrionment Variable (FALCON_CLOUD) blank, and select the same option (us-2) in the dialog that the script generates.

**Comment by PaulYounan** [comment]
FYI - "Autodiscover" works as well.

**Comment by redhatrises** [comment]
> Hi Gabe, thanks for the response.
> 
> 
> 
> I'm setting an environment variable in MacOS.
> 
> 
> 
> Curiously, this works if I leave the ENV Variable (FALCON_CLOUD) blank, and select the same option (us-2) in the dialog that the script generates. 

Are you setting the env variable as FALCON_CLOUD="us-2" ?

**Comment by PaulYounan** [comment]
Thanks again, that worked.  I was using the full url as given in the API Key creation step.  Thanks for your help!

**Comment by PaulYounan** [comment]
Can we put a note in the page to help anyone else who faces the same issue in the future, probably just under the picture that gives the API Key Base URL?

**Comment by ffalor** [comment]
Thank you @PaulYounan for the report. I agree, I'll add something to clarify this.
